workflows:
  web-workflow:
    name: Roluna Connect — Web
    max_build_duration: 30
    instance_type: linux
    environment:
      flutter: stable
    scripts:
      - name: Instalar dependências
        script: |
          flutter pub get
      - name: Build Web (release)
        script: |
          flutter build web --release
    artifacts:
      - build/web/**
    publishing:
      email:
        recipients: []
